# Generated by Django 4.2.5 on 2023-10-27 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 27, 7, 10, 15, 456027, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
